name: "Composer Require Checker"

on:
    pull_request:
    push:
        branches:
            - "master"
jobs:
    composer-require-checker:
        name: composer-require-checker check
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - name: "Install PHP"
              uses: shivammathur/setup-php@v2
              with:
                  tools: composer-require-checker

            - name: "Get composer cache directory"
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: "Cache composer dependencies"
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: "Install dependencies"
              run: |
                  composer install --no-progress --no-scripts --no-dev

            - name: "Run composer-require-checker check"
              run: composer-require-checker check composer.json
